[wokwi]
version = 1
firmware = '.pio\build\esp32doit-devkit-v1\firmware.bin'
elf = '.pio\build\esp32doit-devkit-v1\firmware.elf'

[mqtt]
broker = "test.mosquitto.org"
topics = ["sala/temperatura", "sala/humedad", "sala/led", "sala/luz"]
